In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
x = dataset.iloc[:, 3:13].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y = dataset.iloc[:, 13].values

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [10]:
labelencoder_x_1 = LabelEncoder()

In [11]:
x[:, 1] = labelencoder_x_1.fit_transform(x[:, 1])

In [12]:
labelencoder_x_2 = LabelEncoder()

In [13]:
x[:, 2] = labelencoder_x_2.fit_transform(x[:, 2])

In [14]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
onehotencoder = OneHotEncoder(categorical_features = [1])

In [16]:
x = onehotencoder.fit_transform(x).toarray()

In [17]:
x = x[:, 1:] 

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 0)

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
sc = StandardScaler()

In [22]:
x_train = sc.fit_transform(x_train)

In [23]:
x_test = sc.transform(x_test)

In [24]:
import keras

Using TensorFlow backend.


In [25]:
from keras.models import Sequential

In [26]:
from keras.layers import Dense

In [27]:
#classifier = Sequential()

In [28]:
#classifier.add(Dense(units = 6, kernel_initializer ='uniform', activation = 'relu', input_dim = 11))

In [29]:
#classifier.add(Dense(units = 6, kernel_initializer ='uniform', activation = 'relu'))

In [30]:
#classifier.add(Dense(units = 1, kernel_initializer ='uniform', activation = 'sigmoid'))

In [31]:
#classifier.compile(optimizer = 'adam', loss ='binary_crossentropy', metrics = ['accuracy'])

In [32]:
#classifier.fit(x_train, y_train, batch_size = 10, epochs =100)

In [33]:
#y_pred = classifier.predict(x_test)

In [34]:
#y_pred = (y_pred > 0.5)

In [35]:
#from sklearn.metrics import confusion_matrix

In [36]:
#cm = confusion_matrix(y_test, y_pred)

In [37]:
#cm

In [38]:
#(1521+205)/2000

In [39]:
#new_prediction =classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1,40, 3, 60000, 2, 1, 1, 50000]])))

In [40]:
#new_prediction = (new_prediction > 0.5)

In [41]:
#new_prediction

In [42]:
#from keras.wrappers.scikit_learn import KerasClassifier
#from sklearn.model_selection import cross_val_score
#from keras.models import Sequential
#from keras.layers import Dense

In [43]:
#def build_classifier():
 #classifier = Sequential()
 #classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
 #classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
 #classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
 #classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
 #return classifier

In [44]:
#classifier = KerasClassifier(build_fn = build_classifier,batch_size = 10, epochs = 90)

In [45]:
#accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10, n_jobs = 1)

In [46]:
#mean = accuracies.mean()

In [47]:
#variance = accuracies.std()

In [59]:
#If we reach overfiting by using dropout we can avoid it

In [48]:
#from keras.layers import Dropout

In [49]:
#classifier = Sequential()

In [52]:
#classifier.add(Dense(units = 6, kernel_initializer ='uniform', activation = 'relu', input_dim = 11))


In [53]:
#classifier.add(Dropout(p = 0.1))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  """Entry point for launching an IPython kernel.


In [54]:
#classifier.add(Dense(units = 6, kernel_initializer ='uniform', activation = 'relu'))

In [55]:
#classifier.add(Dropout(p = 0.1))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  """Entry point for launching an IPython kernel.


In [56]:
#classifier.add(Dense(units = 1, kernel_initializer ='uniform', activation = 'sigmoid'))

In [58]:
#classifier.compile(optimizer = 'adam', loss ='binary_crossentropy', metrics = ['accuracy'])

In [60]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense


In [61]:
def build_classifier(optimizer):
 classifier = Sequential()
 classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
 classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
 classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
 classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
 return classifier

In [62]:
classifier = KerasClassifier(build_fn = build_classifier)

In [63]:
parameters = {'batch_size': [25, 32],
 'epochs': [100, 500],
 'optimizer': ['adam', 'rmsprop']}

In [64]:
grid_search = GridSearchCV(estimator = classifier,
 param_grid = parameters,
scoring = 'accuracy',
cv = 10)

In [65]:
grid_search = grid_search.fit(x_train, y_train)

Epoch 1/100
7200/7200 [==============================] - 1s 134us/step - loss: 0.5609 - acc: 0.7954
Epoch 2/100
7200/7200 [==============================] - 1s 78us/step - loss: 0.4323 - acc: 0.7971
Epoch 3/100
7200/7200 [==============================] - 1s 89us/step - loss: 0.4268 - acc: 0.7971
Epoch 4/100
7200/7200 [==============================] - 1s 84us/step - loss: 0.4235 - acc: 0.7971
Epoch 5/100
7200/7200 [==============================] - 1s 87us/step - loss: 0.4211 - acc: 0.7971
Epoch 6/100
7200/7200 [==============================] - 1s 93us/step - loss: 0.4190 - acc: 0.7999
Epoch 7/100
7200/7200 [==============================] - 1s 103us/step - loss: 0.4173 - acc: 0.8193
Epoch 8/100
7200/7200 [==============================] - 1s 104us/step - loss: 0.4164 - acc: 0.8257
Epoch 9/100
7200/7200 [==============================] - 1s 103us/step - loss: 0.4152 - acc: 0.8272
Epoch 10/100
7200/7200 [==============================] - 1s 118us/step - loss: 0.4142 - acc: 0.8279
Epoc

7200/7200 [==============================] - 1s 120us/step - loss: 0.3968 - acc: 0.8361
Epoch 83/100
7200/7200 [==============================] - 1s 113us/step - loss: 0.3963 - acc: 0.8358
Epoch 84/100
7200/7200 [==============================] - 1s 93us/step - loss: 0.3965 - acc: 0.8353
Epoch 85/100
7200/7200 [==============================] - 1s 111us/step - loss: 0.3963 - acc: 0.8357
Epoch 86/100
7200/7200 [==============================] - 1s 113us/step - loss: 0.3960 - acc: 0.8356
Epoch 87/100
7200/7200 [==============================] - 1s 113us/step - loss: 0.3960 - acc: 0.8357
Epoch 88/100
7200/7200 [==============================] - 1s 122us/step - loss: 0.3959 - acc: 0.8371
Epoch 89/100
7200/7200 [==============================] - 1s 130us/step - loss: 0.3956 - acc: 0.8354
Epoch 90/100
7200/7200 [==============================] - 1s 121us/step - loss: 0.3959 - acc: 0.8369
Epoch 91/100
7200/7200 [==============================] - 1s 113us/step - loss: 0.3957 - acc: 0.8357
Epoc

7200/7200 [==============================] - 1s 90us/step - loss: 0.3451 - acc: 0.8608
Epoch 64/100
7200/7200 [==============================] - 1s 83us/step - loss: 0.3442 - acc: 0.8608
Epoch 65/100
7200/7200 [==============================] - 1s 86us/step - loss: 0.3442 - acc: 0.8621
Epoch 66/100
7200/7200 [==============================] - 1s 81us/step - loss: 0.3443 - acc: 0.8612
Epoch 67/100
7200/7200 [==============================] - 1s 86us/step - loss: 0.3449 - acc: 0.8622
Epoch 68/100
7200/7200 [==============================] - 1s 90us/step - loss: 0.3436 - acc: 0.8617
Epoch 69/100
7200/7200 [==============================] - 1s 83us/step - loss: 0.3438 - acc: 0.8617
Epoch 70/100
7200/7200 [==============================] - 1s 100us/step - loss: 0.3441 - acc: 0.8610
Epoch 71/100
7200/7200 [==============================] - 1s 81us/step - loss: 0.3441 - acc: 0.8611
Epoch 72/100
7200/7200 [==============================] - 1s 90us/step - loss: 0.3438 - acc: 0.8615
Epoch 73/100

7200/7200 [==============================] - 1s 96us/step - loss: 0.3386 - acc: 0.8614
Epoch 45/100
7200/7200 [==============================] - 1s 91us/step - loss: 0.3386 - acc: 0.8608
Epoch 46/100
7200/7200 [==============================] - 1s 98us/step - loss: 0.3386 - acc: 0.8617
Epoch 47/100
7200/7200 [==============================] - 1s 84us/step - loss: 0.3382 - acc: 0.8610
Epoch 48/100
7200/7200 [==============================] - 1s 87us/step - loss: 0.3386 - acc: 0.8610
Epoch 49/100
7200/7200 [==============================] - 1s 89us/step - loss: 0.3382 - acc: 0.8635
Epoch 50/100
7200/7200 [==============================] - 1s 94us/step - loss: 0.3376 - acc: 0.8629
Epoch 51/100
7200/7200 [==============================] - 1s 99us/step - loss: 0.3379 - acc: 0.8622
Epoch 52/100
7200/7200 [==============================] - 1s 83us/step - loss: 0.3377 - acc: 0.8621
Epoch 53/100
7200/7200 [==============================] - 1s 90us/step - loss: 0.3372 - acc: 0.8621
Epoch 54/100


KeyboardInterrupt: 

In [ ]:
best_parameters = grid_search.best_params_

In [ ]:
best_accuracy = grid_search.best_score_